# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DisasterGuide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DisasterGuide
  pod 'Alamofire', '~> 4.7'
  pod 'PromiseKit', '~> 6.0'
  pod 'TextFieldEffects'
  pod 'SwiftyJSON'
  # pod 'ChameleonFramework/Swift'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'GoogleMaps'
  pod 'Parse'
  pod 'Font-Awesome-Swift', '~> 1.7.2'


  target 'DisasterGuideTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DisasterGuideUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
    end

end
